{{- if .Values.app.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "automation-server-test.fullname" . }}
  labels:
    app: {{ include "automation-server-test.labels.app" . }}
    chart: {{ include "automation-server-test.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  {{- if .Values.app.rbac.events }}
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - "get"
    - "list"
  {{- end }}
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - "create"
    - "get"
    - "delete"
    - "list"
    - "watch"
- apiGroups:
    - ""
  resources:
    - "pods/log"
  verbs:
    - "get"
    - "list"
- apiGroups:
    - ""
  resources:
    - "pods/exec"
  verbs:
    - "create"
    - "get"
  {{- end }}